<<<<<<< HEAD
name: Run Checks on PR
=======
name: 1.1 Run Checks on PR
>>>>>>> 9ff487a (Initial commit)

on:
  pull_request:
    branches:
      - main
<<<<<<< HEAD
=======
  workflow_call: {}
>>>>>>> 9ff487a (Initial commit)

permissions:
  actions: write
  checks: write
  contents: read
  security-events: write
  pull-requests: write

env:
  CI: true
  SITE_DIR: site
  TETRIS_APP_HOST: "127.0.0.1"
  TETRIS_APP_PORT: "8080"
  TETRIS_APP_PATH: "github-devsecops-fundamentals"

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/setup-node@v3
        with:
          node-version: 20

<<<<<<< HEAD
      - name: Install Dependencies
=======
      - name: Install dependencies
>>>>>>> 9ff487a (Initial commit)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.ci.txt
          npm ci
<<<<<<< HEAD
          # Install browsers for running functional tests
=======
>>>>>>> 9ff487a (Initial commit)
          npx playwright install --with-deps chromium

      - name: Build
        run: |
          python -m mkdocs build --clean --strict --verbose --site-dir '${{ env.SITE_DIR }}'

<<<<<<< HEAD
      - name: Functional Test
        run: npx playwright test

      - name: Upload Functional Test Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
=======
      - name: Functional test
        run: |
          npx playwright test
>>>>>>> 9ff487a (Initial commit)
